### ISSUE TITLE
Add Documenter-based automatic documentation hosting

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/Automa.jl#70]
I removed documentation hosting in one of the last commits (and it didn't work before, anyway), so that needs to be restored

**Comment by kescobo** [comment]
I've done this a bunch, so I can take a stab if you'd like It's a pain in the ass, and I have to look up stuff every time, but it's been getting quicker.

Can you give me admin rights to the repo if I don't have them already? Need to set up secrets and stuff and it's easier to just do it than to tell you what to do.

**Comment by jakobnissen** [comment]
That would be grand :+1:. I've given you admin access to the repo now.
